service: myserverlessproject

provider:
    name: aws
    runtime: nodejs10.x
    
    region: us-east-1

plugins:
    - serverless-s3-sync
    

package:
    individually: true

custom:
    s3Sync:
        - bucketName: lakshmi12345
          localDir: UploadData

functions:
    getUser:
        handler: lambdas/getUser.handler
        events:
            - http:
                  path: get-user/{ID}
                  method: GET
                  cors: true

resources:
    Resources:
        DemoBucketUpload:
            Type: AWS::S3::Bucket
            Properties:
                BucketName: lakshmi12345
